from api.schemas import LandmarkEmotionPrior


LANDMARK_PRIORS = {
    "cafe": LandmarkEmotionPrior(
        landmark_type="cafe",
        emotion_tags=["calm", "recovery", "familiar"],
        fatigue_modifier=-3,
        crowd_modifier=-2,
        noise_modifier=-1,
        recovery_bonus=7,
        reason="Cafes are useful cold-start recovery stops for tired or overloaded users.",
    ),
    "school": LandmarkEmotionPrior(
        landmark_type="school",
        emotion_tags=["crowded", "stressful", "familiar"],
        fatigue_modifier=1,
        crowd_modifier=4,
        noise_modifier=2,
        recovery_bonus=0,
        reason="School areas can be familiar, but they often add crowd and schedule stress.",
    ),
    "library": LandmarkEmotionPrior(
        landmark_type="library",
        emotion_tags=["calm", "recovery", "familiar"],
        fatigue_modifier=-2,
        crowd_modifier=-2,
        noise_modifier=-3,
        recovery_bonus=5,
        reason="Libraries are quiet, familiar decompression places for focused recovery.",
    ),
    "convenience_store": LandmarkEmotionPrior(
        landmark_type="convenience_store",
        emotion_tags=["familiar", "walkable"],
        fatigue_modifier=-1,
        crowd_modifier=0,
        noise_modifier=0,
        recovery_bonus=2,
        reason="Convenience stores are low-effort stops, but not strongly restorative.",
    ),
    "restaurant": LandmarkEmotionPrior(
        landmark_type="restaurant",
        emotion_tags=["crowded", "familiar"],
        fatigue_modifier=0,
        crowd_modifier=2,
        noise_modifier=2,
        recovery_bonus=2,
        reason="Restaurants can help with basic needs but often add crowd and noise load.",
    ),
    "shopping_mall": LandmarkEmotionPrior(
        landmark_type="shopping_mall",
        emotion_tags=["crowded", "high_noise", "stressful"],
        fatigue_modifier=2,
        crowd_modifier=5,
        noise_modifier=4,
        recovery_bonus=0,
        reason="Shopping malls are useful but usually high-stimulation environments.",
    ),
    "nightlife": LandmarkEmotionPrior(
        landmark_type="nightlife",
        emotion_tags=["crowded", "high_noise", "stressful"],
        fatigue_modifier=3,
        crowd_modifier=5,
        noise_modifier=5,
        recovery_bonus=0,
        reason="Nightlife streets tend to be loud, crowded, and emotionally expensive.",
    ),
    "gym": LandmarkEmotionPrior(
        landmark_type="gym",
        emotion_tags=["familiar", "walkable"],
        fatigue_modifier=2,
        crowd_modifier=1,
        noise_modifier=1,
        recovery_bonus=1,
        reason="Gyms can be familiar but physically demanding for tired users.",
    ),
    "government_office": LandmarkEmotionPrior(
        landmark_type="government_office",
        emotion_tags=["stressful", "familiar"],
        fatigue_modifier=1,
        crowd_modifier=2,
        noise_modifier=1,
        recovery_bonus=0,
        reason="Administrative stops often add waiting and task pressure.",
    ),
    "park": LandmarkEmotionPrior(
        landmark_type="park",
        emotion_tags=["calm", "recovery", "walkable"],
        fatigue_modifier=-4,
        crowd_modifier=-3,
        noise_modifier=-2,
        recovery_bonus=8,
        reason="Parks usually provide calm recovery value for cold-start scoring.",
    ),
    "river": LandmarkEmotionPrior(
        landmark_type="river",
        emotion_tags=["calm", "recovery", "walkable"],
        fatigue_modifier=-3,
        crowd_modifier=-2,
        noise_modifier=-2,
        recovery_bonus=7,
        reason="Riverside routes tend to support decompression and steady walking.",
    ),
    "university": LandmarkEmotionPrior(
        landmark_type="university",
        emotion_tags=["familiar", "walkable"],
        fatigue_modifier=-1,
        crowd_modifier=1,
        noise_modifier=1,
        recovery_bonus=2,
        reason="University areas are familiar but can become moderately busy.",
    ),
    "transit_hub": LandmarkEmotionPrior(
        landmark_type="transit_hub",
        emotion_tags=["crowded", "stressful", "high_noise"],
        fatigue_modifier=2,
        crowd_modifier=5,
        noise_modifier=4,
        recovery_bonus=0,
        reason="Transit hubs reduce travel time but often increase crowd stress.",
    ),
    "main_road": LandmarkEmotionPrior(
        landmark_type="main_road",
        emotion_tags=["high_noise", "walkable"],
        fatigue_modifier=1,
        crowd_modifier=2,
        noise_modifier=4,
        recovery_bonus=0,
        reason="Main roads are efficient but noisy.",
    ),
    "side_street": LandmarkEmotionPrior(
        landmark_type="side_street",
        emotion_tags=["calm", "walkable"],
        fatigue_modifier=-2,
        crowd_modifier=-2,
        noise_modifier=-2,
        recovery_bonus=3,
        reason="Side streets are usually calmer and easier to tolerate.",
    ),
    "medical": LandmarkEmotionPrior(
        landmark_type="medical",
        emotion_tags=["stressful"],
        fatigue_modifier=1,
        crowd_modifier=1,
        noise_modifier=0,
        recovery_bonus=0,
        reason="Medical stops can be necessary but rarely feel restorative.",
    ),
    "commercial": LandmarkEmotionPrior(
        landmark_type="commercial",
        emotion_tags=["crowded", "walkable"],
        fatigue_modifier=1,
        crowd_modifier=3,
        noise_modifier=2,
        recovery_bonus=1,
        reason="Commercial areas are useful but can add crowd load.",
    ),
}


def get_landmark_emotion_prior(landmark_type: str) -> LandmarkEmotionPrior:
    return LANDMARK_PRIORS.get(landmark_type, LANDMARK_PRIORS["commercial"])


def get_landmark_priors(landmark_types: list[str]) -> list[LandmarkEmotionPrior]:
    return [get_landmark_emotion_prior(landmark_type) for landmark_type in landmark_types]
